[package]
name = "green_copper_runtime"
version = "0.0.1"
authors = ["info@hirofa.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

default = ["all"]

all = ["io", "db", "com", "libs"]

io = ["gpio", "fs"]
libs = ["commonjs"]
db = ["mysql"]

fs = []
gpio = ["gpio-cdev", "futures"]
mysql = ["mysql_lib"]

com = ["http"]
http = ["ureq"]

commonjs = []



[dependencies]
quickjs_runtime = { git = 'https://github.com/HiRoFa/quickjs_es_runtime' }
#quickjs_runtime = "0.2.1"
#quickjs_runtime = { path = '../quickjs_es_runtime'}
libquickjs-sys = "0.9.0"
#libquickjs-sys = {git= "https://github.com/HiRoFa/quickjs-rs"}
libc = "0.2"
lazy_static = "1.4.0"
log = "0.4.8"
simple-logging = "2.0.2"
rand = "0.7.0"
num_cpus = "1.0"
backtrace = "0.3.56"
url = "2.2.1"

ureq = {version = "1.*", features=["cookies", "json", "charset", "tls", "socks-proxy"], optional = true}
gpio-cdev = {git = "https://github.com/rust-embedded/gpio-cdev", optional = true, features = ["async-tokio", "futures"]}
futures = {version = "0.3", optional = true}
mysql_lib = {package="mysql", version = "20.1",  optional = true}
